//! Domain types shared by the active agentic runtime and staged workflow transitions.
//!
//! The key teaching idea in this module is *state-indexed data*: [`crate::types::Artifact<S>`]
//! carries both payload and lifecycle state in its type parameter.
//!
//! - [`crate::types::Blueprint`] captures intent.
//! - [`crate::types::Draft`] captures generated Python code.
//! - [`crate::types::Product`] captures successful output.
//! - [`crate::types::Broken`] captures failing code plus diagnosis.
//!
//! This approach keeps illegal transitions hard to express at compile time.
//! For example, you cannot use a [`crate::types::Draft`]
//! with an [`crate::types::Artifact<crate::types::Blueprint>`] value.

use crate::errors::GenError;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

// 🎓 TEACHING POINT: Sealed Typestates
// We "seal" the state trait so no one outside this module can create invalid states.
// By keeping the `Sealed` trait private (inside a private module), only types in *this* module
// can implement it.
mod sealed {
    pub trait Sealed {}
}

/// Convenience alias for the Claude-capable Rig agent used by this crate.
///
/// This alias keeps signatures readable in modules that compose multiple tools and
/// capabilities around a single LLM persona.
///
/// # Examples
///
/// ```ignore
/// use build123d_cad::types::ClaudeAgent;
///
/// // `ClaudeAgent` is an alias to a concrete `rig::agent::Agent<...>` type.
/// let _agent_type_name = std::any::type_name::<ClaudeAgent>();
/// ```
pub type ClaudeAgent = rig::agent::Agent<rig::providers::anthropic::completion::CompletionModel>;

/// Marker trait for legal artifact lifecycle states.
///
/// This trait is sealed to prevent external crates from introducing state types
/// that bypass the transition rules encoded by this crate.
///
/// # Examples
///
/// ```
/// use build123d_cad::types::{Blueprint, State};
///
/// fn accepts_state<S: State>(_: &S) {}
///
/// let b = Blueprint { prompt: "A cube".to_string() };
/// accepts_state(&b);
/// ```
pub trait State: sealed::Sealed + std::fmt::Debug {}

// --- The Container ---

/// State-indexed container representing a CAD work item.
///
/// `Artifact<S>` combines shared identity (`name`) with state-specific payload (`state`).
/// The generic parameter is the core safety mechanism:
///
/// - `Artifact<Blueprint>` means "intent captured, no code yet".
/// - `Artifact<Draft>` means "code generated, pending validation/review".
/// - `Artifact<Product>` means "output generated successfully".
/// - `Artifact<Broken>` means "failed and needs repair".
///
/// This is effectively a lightweight typestate model without runtime tags.
///
/// # Examples
///
/// ```
/// use build123d_cad::types::{Artifact, Blueprint};
///
/// let idea = Artifact {
///     name: "my_part".to_string(),
///     state: Blueprint {
///         prompt: "A parametric flange with bolt holes".to_string(),
///     },
/// };
///
/// assert!(idea.state.prompt.contains("flange"));
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Artifact<S: State> {
    /// A human-readable identifier for this artifact (e.g., "parametric_flange").
    pub name: String,
    /// The state-specific data (e.g., the prompt, the code, or the file path).
    pub state: S,
}

// --- The States ---

/// Initial design intent, directly sourced from user input.
///
/// A [`Blueprint`] intentionally keeps structure minimal. It captures *what the user
/// wants* before any translation to executable build123d code occurs.
///
/// # Examples
///
/// ```
/// use build123d_cad::types::Blueprint;
///
/// let blueprint = Blueprint {
///     prompt: "A hollow cylinder with 6 equally spaced holes".to_string(),
/// };
///
/// assert!(blueprint.prompt.contains("cylinder"));
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Blueprint {
    /// The natural language description of what to build.
    pub prompt: String,
}
impl sealed::Sealed for Blueprint {}
impl State for Blueprint {}

/// Generated build123d Python source awaiting validation or execution.
///
/// Treat this type as "candidate code": syntactically plausible output that must pass
/// linting, runtime checks, and review consensus before becoming a [`Product`].
///
/// # Examples
///
/// ```
/// use build123d_cad::types::Draft;
///
/// let draft = Draft {
///     code: "from build123d import *\n\nwith BuildPart() as part:\n    Box(10, 10, 10)".to_string(),
/// };
///
/// assert!(draft.code.contains("BuildPart"));
/// ```
#[derive(Debug)]
pub struct Draft {
    /// The raw Python source code generated by the LLM.
    pub code: String,
}
impl sealed::Sealed for Draft {}
impl State for Draft {}

/// Successful generation result pointing at a produced CAD artifact on disk.
///
/// This state is terminal for the staged pipeline: once a valid file path is
/// present, downstream code can hand off to external pipelines (simulation, packaging,
/// manufacturing review).
///
/// # Examples
///
/// ```
/// use build123d_cad::types::Product;
/// use std::path::PathBuf;
///
/// let product = Product {
///     path: PathBuf::from("/tmp/bracket.step"),
/// };
///
/// assert_eq!(product.path.extension().and_then(|ext| ext.to_str()), Some("step"));
/// ```
#[derive(Debug)]
pub struct Product {
    /// The absolute path to the generated CAD file (`.step`, `.stl`, etc.).
    pub path: PathBuf,
}
impl sealed::Sealed for Product {}
impl State for Product {}

/// Failure state capturing both failing code and diagnosis.
///
/// Keeping the failing source and error together allows repair logic to generate
/// targeted patches rather than regenerating entire scripts from scratch.
/// See the active orchestrator retry path for consumers of this state.
///
/// # Examples
///
/// ```
/// use build123d_cad::errors::GenError;
/// use build123d_cad::types::Broken;
///
/// let broken = Broken {
///     code: "with BuildPart( as part:".to_string(),
///     diagnosis: GenError::AgentFailure("SyntaxError".to_string()),
/// };
///
/// assert!(broken.code.contains("BuildPart"));
/// ```
#[derive(Debug)]
pub struct Broken {
    /// The code that caused the failure.
    pub code: String,
    /// The specific reason why the code failed (e.g., SyntaxError).
    pub diagnosis: GenError,
}
impl sealed::Sealed for Broken {}
impl State for Broken {}
